### ISSUE TITLE
Supports Vue.js v3

### ISSUE THREAD

**Issue by ota-meshi** [future-architect/eslint-plugin-vue-scoped-css#34]
Refs [RFC0023](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0023-scoped-styles-changes.md)

Supports the following CSS:

```css
/* deep selectors */
::v-deep(.foo) {}

/* targeting slot content */
::v-slotted(.foo) {}

/* one-off global rule */
::v-global(.foo) {}
```

---

Refs [RFC0018](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0018-transition-class-change.md)

Supports the following classes:

```css
.v-enter-from, .v-leave-to {
  opacity: 0;
}
.v-leave-from, .v-enter-to {
  opacity: 1
}
```
