### ISSUE TITLE
False "unused selector" for SCSS Extend

### ISSUE THREAD

**Issue by DragonWhisperer** [future-architect/eslint-plugin-vue-scoped-css#50]
```scss
<style scoped lang="scss">
%title {
  font-size: 2rem;
}
.eng-title {
  @extend %title;
}
</style>
```

I get ```The selector `%title` is unused.```
